[package]
name = "stream-ecs-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
deluxe = { version = "0.5", default-features = false, features = ["proc-macro"] }
proc-macro-crate = "1"
